module MAIN ( keyEnable, unlockDoor );
	
	
	output unlockDoor;		// Variable for deciding if passwords match or not.
	input keyEnable;        // this signal will be high for specified time, after the key is inserted.
	wire[31:0] newPass;     // new password that is generated by the random number generator.
	wire[31:0] keyPass;		// Previous/Original password present in the Key.
	wire[31:0] lockPass;	// Previous/Original password present in the Lock.



	wire readKey;
	wire readLock;
	

	initial
	begin
		#50;
		if(unlockDoor == 0) $display("Wrong Password! Thief!! Help!!");
		$finish;
	end
	
	KEY key ( keyEnable, keyPass, readKey, newPass);
	LOCK lock ( lockPass, readLock, newPass);
	PASS_CHECK passwordCheck ( keyPass, lockPass, unlockDoor, readLock, readKey );
	RPG rpg ( newPass, unlockDoor, keyEnable );

	

endmodule